# Generated by Django 4.2.2 on 2025-12-14 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('retailer', 'Retailer')], max_length=20)),
                ('alert_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('any_change', 'Any Price Change')], default='price_drop', max_length=20)),
                ('threshold_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Optional % drop threshold', max_digits=5, null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='True = paid subscription')),
                ('is_free_tier', models.BooleanField(default=True, help_text='True = free-tier subscription')),
                ('is_active', models.BooleanField(default=False, help_text='Controls whether alerts are sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.retailer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('target_type', 'product')), models.Q(('category__isnull', False), ('target_type', 'category')), models.Q(('retailer__isnull', False), ('target_type', 'retailer')), _connector='OR'), name='subscription_target_consistency'),
        ),
    ]
