# Generated by Django 4.2.2 on 2025-12-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
