# Generated by Django 4.2.2 on 2025-12-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alertlog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscription_target_consistency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='threshold_pct',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_free_tier',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
