# Generated by Django 4.2.2 on 2025-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_free_tier',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
