# Generated by Django 4.2.2 on 2025-12-14 13:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_phone_number_whatsappauthcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsAppAuthCode',
            new_name='LoginOTP',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
