# Generated by Django 4.2.2 on 2025-12-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
