# Generated by Django 4.2.2 on 2025-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
