# Generated by Django 4.2.2 on 2025-12-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_grace_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
