# Generated by Django 4.2.2 on 2026-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_deal_upsert'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='http_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='pages_scraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='products_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='products_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
