# Generated by Django 4.2.2 on 2026-06-05 18:19

from django.db import migrations


def seed_chandarana(apps, schema_editor):
    Retailer = apps.get_model('core', 'Retailer')
    Retailer.objects.get_or_create(name='Chandarana')


def reverse_seed(apps, schema_editor):
    pass  # leave the row in place on rollback


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_scraper_run_stats'),
    ]

    operations = [
        migrations.RunPython(seed_chandarana, reverse_seed),
    ]
