apiVersion: v1
kind: ConfigMap
metadata:
  name: bargainhunters-config
  namespace: bargainhunters
data:
  DJANGO_SETTINGS_MODULE: "catalogue.settings"
  ALLOWED_HOSTS: "bargainhunters.co.ke,www.bargainhunters.co.ke"
  DEBUG: "False"
  STATIC_ROOT: "/app/staticfiles"
  MEDIA_ROOT: "/app/media"
  CORS_ALLOWED_ORIGINS: "https://bargainhunters.co.ke,https://www.bargainhunters.co.ke"
  CSRF_TRUSTED_ORIGINS: "https://bargainhunters.co.ke,https://www.bargainhunters.co.ke"
