# Generated by Django 4.2.2 on 2026-06-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_alertlog_is_read'),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listoptimisationresult',
            name='branch_plan',
            field=models.JSONField(default=dict, help_text='Full optimisation result — see docstring above for shape'),
        ),
        migrations.AlterField(
            model_name='listoptimisationresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listoptimisationresult',
            name='mode',
            field=models.CharField(help_text='The mode that was used when this result was computed', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum spend in KES — used only when mode=budget', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this deal was found', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='core.retailerbranch'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='is_matched',
            field=models.BooleanField(default=False, help_text='True once product FK has been resolved from raw_query'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='match_score',
            field=models.FloatField(blank=True, help_text='0.0–1.0 — fuzzy/category match confidence shown in the UI', null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the list'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='raw_query',
            field=models.CharField(help_text='Exactly what the user typed into the search box', max_length=500),
        ),
        migrations.AlterField(
            model_name='userbranchpreference',
            name='home_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='User home/work latitude — used to sort nearby branches', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userbranchpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbranchpreference',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first in branch selector'),
        ),
    ]
